#
# Copyright (c) 2025 William Guo <github.com/gw826943555>
#
# This is free software, licensed under the GNU Lesser General Public License v3.0.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for EasyTier
LUCI_DEPENDS:=+easytier
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature